config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, :controllers => {:registrations => "users"}

  root "home#index"

  get 'users/:id/commutes/new' => 'commute#new', as: 'new_commute'
  post 'users/:id/commutes/create' => 'commute#create', as: 'commute'

  get 'users/:user_id/commutes/:id/edit' => 'commute#edit', as: 'edit_commute'
  put 'users/:user_id/commutes/:id' => 'commute#update'
  patch 'users/:user_id/commutes/:id' => 'commute#update'

  post 'drivers/create' => 'driver#create', as: 'driver'
  get 'drivers/:id/edit' => 'driver#edit', as: 'edit_driver'

  post 'riders/create' => 'rider#create', as: 'rider'
  get 'riders/:id/edit' => 'rider#edit', as: 'edit_rider'

  get 'users/:id/inbox' => 'message#index', as: 'inbox'

  post 'users/:id/messages/create' => 'message#create', as: 'message'

  get 'messages/:id' => 'message#destroy', as: 'destroy_message'

  get 'my-rideshare/' => 'rideshare#show', as: 'show_rideshare'

  put 'rideshare/:id/accept' => 'rideshare#update', as: 'accept_rideshare'
  patch 'rideshare/:id/accept' => 'rideshare#update'

  get 'rideshare/:id/remove' => 'rideshare#remove', as: 'remove_rider'

  get 'about' => 'home#about', as: 'about'

end

app/models/commute.rb
class Commute < ActiveRecord::Base
  belongs_to :user
  has_one :driver
  has_one :rider
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :user
  belongs_to :commute

  has_many :rideshares
  has_many :riders, through: :rideshares
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  belongs_to :user
  belongs_to :commute

  has_one :rideshare
  has_one :driver, through: :rideshares
end

app/models/rideshare.rb
class Rideshare < ActiveRecord::Base
  belongs_to :driver
  belongs_to :rider
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages_as_sender, class_name: 'Message', foreign_key: 'sender_id'
  has_many :messages_as_recipient, class_name: 'Message', foreign_key: 'recipient_id'

  has_one :commute

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def messages
    messages_as_sender + messages_as_recipient
  end
end

app/controllers/commute_controller.rb
class CommuteController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @user = User.find(current_user.id)
    @commute = @user.create_commute(commute_params)

    redirect_to edit_commute_path(@user, @commute)
  end

  def edit
    @commute = Commute.find(params[:id])

    @commutes = Commute.where("user_id != #{current_user.id}")

    @driver = Driver.new
    @message = Message.new
    @rider = Rider.new
  end

  def new
    @commute = Commute.new
  end

  def update
    commute = Commute.find(current_user.id)
    commute.update(commute_params)
    redirect_to edit_commute_path(current_user, commute)
  end

  private
  def commute_params
    params.require(:commute).permit!
  end
end

app/controllers/driver_controller.rb
class DriverController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(current_user.id)
    user.commute.create_driver(driver_params)

    3.times do
      Rideshare.create({
          driver_id: user.commute.driver.id
        })
    end

    redirect_to edit_driver_path(user.commute.driver)
  end

  def edit
    @driver = Driver.find(current_user.commute.driver.id)

    @message = Message.new

    @riders = Rider.where(looking: true)
  end

  private

  def driver_params
    params.require(:driver).permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def inbox
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(current_user.id)
    @user.messages_as_sender.create(message_params)

    redirect_to inbox_path(current_user)
  end

  def destroy
    mail = Message.find(params[:id])
    mail.destroy

    redirect_to inbox_path(current_user)
  end

  def index
    user = User.find(current_user.id)

    @message = Message.new

    @inbox = user.messages_as_recipient.order('invite DESC, created_at DESC')
    @outbox = user.messages_as_sender.order('created_at DESC')
  end

  def reply

  end

  private
  def message_params
    params.require(:message).permit!
  end
end

app/controllers/rider_controller.rb
class RiderController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(current_user.id)
    user.commute.create_rider(rider_params)
    redirect_to edit_rider_path(user.commute.rider)
  end

  def edit
    @rider = Rider.find(current_user.commute.rider.id)

    @drivers = Driver.all

    @message = Message.new
  end

  private

  def rider_params
    params.require(:rider).permit!
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/commute_helper.rb
module CommuteHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/rider_helper.rb
module RiderHelper
end

app/helpers/rideshare_helper.rb
module RideshareHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Carpool Austin</h5>
        <p class="grey-text text-lighten-4"> 716 N Congress Ave #100, Austin, TX 78701</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <% if current_user %>
            <% if current_user.commute %>
              <li><%= link_to "Edit Commute", edit_commute_path(current_user, current_user.commute), class: "grey-text text-lighten-3" %></li>
            <% elsif current_user %>
              <li><%= link_to "New Commute", new_commute_path(current_user), class: "grey-text text-lighten-3" %></li>
            <% end %>
            <% if current_user.commute && current_user.commute.driver %>
              <li><%= link_to 'Find Riders', edit_driver_path(current_user.commute.driver.id), class: "grey-text text-lighten-3" %></li>
              <li><%= link_to 'Show Carpool', show_rideshare_path, class: "grey-text text-lighten-3" if current_user.commute.driver.rideshares %></li>
            <% elsif current_user.commute && current_user.commute.rider %>
              <li><%= link_to 'Find Drivers', edit_rider_path(current_user.commute.rider.id), class: "grey-text text-lighten-3" %></li>
              <li><%= link_to 'Show Carpool', show_rideshare_path, class: "grey-text text-lighten-3" if current_user.commute.rider.rideshare %></li>
            <% end %>
            <li><a class="grey-text text-lighten-3" href="/users/<%= current_user.id %>/inbox">Messages
                <% if current_user.messages_as_recipient.where(read: false).length > 0 %>
                  <span class="new badge red"><%= current_user.messages_as_recipient.where(read: false).length %></span>
                <% end %>
              </a>
            </li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "grey-text text-lighten-3" %></li>
          <% end %>
          <li><a class="grey-text text-lighten-3" href="<%= about_path %>">About Me</a></li>
        <ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2015 Carpool Austin
    </div>
  </div>
</footer>

app/views/layouts/_topbar.html.erb
<!-- Dropdown Navbar -->

<ul id="dropdown1" class="dropdown-content">
	<% if current_user %>
		<% if current_user.commute %>
			<li><%= link_to "Edit Commute", edit_commute_path(current_user, current_user.commute) %></li>
		<% elsif current_user %>
			<li><%= link_to "New Commute", new_commute_path(current_user) %></li>
		<% end %>
		<% if current_user.commute && current_user.commute.driver %>
			<li><%= link_to 'Find Riders', edit_driver_path(current_user.commute.driver.id) %></li>
			<li><%= link_to 'Show Carpool', show_rideshare_path if current_user.commute.driver.rideshares %></li>
		<% elsif current_user.commute && current_user.commute.rider %>
			<li><%= link_to 'Find Drivers', edit_rider_path(current_user.commute.rider.id) %></li>
			<li><%= link_to 'Show Carpool', show_rideshare_path if current_user.commute.rider.rideshare %></li>
		<% end %>
		<li>
			<a href="/users/<%= current_user.id %>/inbox">Messages
				<% if current_user.messages_as_recipient.where(read: false).length > 0 %>
					<span class="new badge red"><%= current_user.messages_as_recipient.where(read: false).length %></span>
				<% end %>
			</a>
		</li>
		<li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
	<% end %>
</ul>

<nav>
	<div class="nav-wrapper">
	    <div class="col s12">
		    <a href="/" class="brand-logo">Carpool Austin</a>
		    <ul class="right hide-on-med-and-down">
		        <!-- Dropdown Trigger -->
		        <% if current_user %>
		        	<li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.username %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
				<% else %>
					<li><%= link_to "Log In", '#log_in_modal', class: "modal-trigger" %></li>
					<li><%= link_to "Sign Up", '#sign_up_modal', class: "modal-trigger" %></li>
				<% end %>
		        <li><a href="<%= about_path %>">About Me</a></li>
		    </ul>
	    </div>
	</div>
</nav>

<!-- End Dropdown Navbar -->

<!-- Log In Modal Structure -->
<div id="log_in_modal" class="modal row">
	<h4>Log In</h4>
	<%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "col s12"}) do |f| %>
		<div class="row">
			<div class="input-field col s12">
				<%= f.label :email %><br />
				<%= f.email_field :email, autofocus: true, class: "validate" %>
			</div>
		</div>
		<div class="row">
			<div class="input-field col s12">
				<%= f.label :password %><br />
				<%= f.password_field :password, autocomplete: "off", class: "validate" %>
			</div>
		</div>

		<% if devise_mapping.rememberable? -%>
			<div class="row">
				<div class="input-field col s12">
	  				<%= f.check_box :remember_me %>
	  				<%= f.label :remember_me %>
				</div>
			</div>
		<% end -%>

		<div class="actions">
	    	<button class="btn waves-effect waves-light" type="submit" name="action">Log In
	    		<i class="mdi-content-send right"></i>
	  		</button>
	  	</div>
	<% end %>
	<%= render "devise/shared/links" %>
</div>
<!-- End of Log In Modal Structure -->

<!-- Sign Up Modal Structure -->
<div id="sign_up_modal" class="modal row">
	<h4>Sign Up</h4>
	<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  		<%= devise_error_messages! %>
  		<div class="row">
	    	<div class="input-field col s6">
	        	<%= f.label :username %><br />
	        	<%= f.text_field :username, autofocus: true, class: "validate" %>
	    	</div>
  			<div class="input-field col s6">
    			<%= f.label :email %><br />
    			<%= f.email_field :email, class: "validate" %>
  			</div>
	    </div>
  		<div class="row">
	  		<div class="input-field col s12">
	    		<%= f.label :password %>
	    		<% if @validatable %>
	    			<em>(<%= @minimum_password_length %> characters minimum)</em>
	    		<% end %><br />
	    		<%= f.password_field :password, autocomplete: "off", class: "validate" %>
	  		</div>
  		</div>
  		<div class="row">
  			<div class="input-field col s12">
    			<%= f.label :password_confirmation %><br />
    			<%= f.password_field :password_confirmation, autocomplete: "off", class: "validate" %>
  			</div>
  		</div>

		<div class="actions">
    		<button class="btn waves-effect waves-light" type="submit" name="action">Sign Up
    			<i class="mdi-content-send right"></i>
  			</button>
  		</div>
	<% end %>
	<%= render "devise/shared/links" %>
</div>
<!-- End of Sign Up Modal Structure -->

<script>
	$(document).ready(function(){
		$(".dropdown-button").dropdown({hover: false});
    	$('.modal-trigger').leanModal();
  	});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
      .toast-alert {background-color: #d91c2d;}
    </style>
  <title>Carpool</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyCWknSnnN9xTWCNlRbRIB1p7QRw9V_S_dI" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/topbar" %>

<!-- <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> -->

<%= yield %>

<%= render "layouts/footer" %>

<script type="text/javascript">
	<% if notice %>
		toast("<%= notice %>", 3000)
	<% end %>

	<% if alert %>
		toast("<%= alert %>", 5000, 'toast-alert')
	<% end %>
</script>

</body>
</html>