config/routes.rb
Rails.application.routes.draw do
  devise_for :users#, :controllers => {:registrations => "users"}

  root "home#index"

  get 'users/:id/commutes/new' => 'commute#new', as: 'new_commute'
  post 'users/:id/commutes/create' => 'commute#create', as: 'commute'

  get 'users/:user_id/commutes/:id/edit' => 'commute#edit', as: 'edit_commute'
  put 'users/:user_id/commutes/:id' => 'commute#update'
  patch 'users/:user_id/commutes/:id' => 'commute#update'

  post 'drivers/create' => 'driver#create', as: 'driver'
  get 'drivers/:id/edit' => 'driver#edit', as: 'edit_driver'

  post 'riders/create' => 'rider#create', as: 'rider'
  get 'riders/:id/edit' => 'rider#edit', as: 'edit_rider'

  get 'users/:id/inbox' => 'message#index', as: 'inbox'

  post 'users/:id/messages/create' => 'message#create', as: 'message'

  get 'messages/:id' => 'message#destroy', as: 'destroy_message'

  get 'my-rideshare/' => 'rideshare#show', as: 'show_rideshare'

  put 'rideshare/:id/accept' => 'rideshare#update', as: 'accept_rideshare'
  patch 'rideshare/:id/accept' => 'rideshare#update'

  get 'rideshare/:id/remove' => 'rideshare#remove', as: 'remove_rider'

  get 'about' => 'home#about', as: 'about'

end

app/models/commute.rb
class Commute < ActiveRecord::Base
  belongs_to :user
  has_one :driver
  has_one :rider
end

app/models/driver.rb
class Driver < ActiveRecord::Base
  belongs_to :user
  belongs_to :commute

  has_many :rideshares
  has_many :riders, through: :rideshares
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  belongs_to :user
  belongs_to :commute

  has_one :rideshare
  has_one :driver, through: :rideshares
end

app/models/rideshare.rb
class Rideshare < ActiveRecord::Base
  belongs_to :driver
  belongs_to :rider
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :messages_as_sender, class_name: 'Message', foreign_key: 'sender_id'
  has_many :messages_as_recipient, class_name: 'Message', foreign_key: 'recipient_id'

  has_one :commute

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def messages
    messages_as_sender + messages_as_recipient
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def authenticate_user!
      redirect_to root_path, alert: "You must login" unless user_signed_in?
    end

   def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
   end
end

app/controllers/commute_controller.rb
class CommuteController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @user = User.find(current_user.id)
    @commute = @user.create_commute(commute_params)

    redirect_to edit_commute_path(@user, @commute)
  end

  def edit
    @commute = Commute.find(params[:id])

    @commutes = Commute.where("user_id != #{current_user.id}")

    @driver = Driver.new
    @message = Message.new
    @rider = Rider.new
  end

  def new
    @commute = Commute.new
  end

  def update
    commute = Commute.find(current_user.id)
    commute.update(commute_params)
    redirect_to edit_commute_path(current_user, commute)
  end

  private
  def commute_params
    params.require(:commute).permit!
  end
end

app/controllers/driver_controller.rb
class DriverController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(current_user.id)
    user.commute.create_driver(driver_params)

    3.times do
      Rideshare.create({
          driver_id: user.commute.driver.id
        })
    end

    redirect_to edit_driver_path(user.commute.driver)
  end

  def edit
    @driver = Driver.find(current_user.commute.driver.id)

    @message = Message.new

    @riders = Rider.where(looking: true)
  end

  private

  def driver_params
    params.require(:driver).permit!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def inbox
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(current_user.id)
    @user.messages_as_sender.create(message_params)

    redirect_to inbox_path(current_user)
  end

  def destroy
    mail = Message.find(params[:id])
    mail.destroy

    redirect_to inbox_path(current_user)
  end

  def index
    user = User.find(current_user.id)

    @message = Message.new

    @inbox = user.messages_as_recipient.order('invite DESC, created_at DESC')
    @outbox = user.messages_as_sender.order('created_at DESC')
  end

  def reply

  end

  private
  def message_params
    params.require(:message).permit!
  end
end

app/controllers/rider_controller.rb
class RiderController < ApplicationController
  before_action :authenticate_user!
  
  def create
    user = User.find(current_user.id)
    user.commute.create_rider(rider_params)
    redirect_to edit_rider_path(user.commute.rider)
  end

  def edit
    @rider = Rider.find(current_user.commute.rider.id)

    @drivers = Driver.all

    @message = Message.new
  end

  private

  def rider_params
    params.require(:rider).permit!
  end
end

app/controllers/rideshare_controller.rb
class RideshareController < ApplicationController
  before_action :authenticate_user!
  
  def remove
    rideshare = Rideshare.find(params[:id])
    rider = Rider.find(rideshare.rider_id)
    rideshare.update(rider_id: nil)
    rider.update(looking: true)
    
    Message.create({
        recipient_id: rideshare.driver.user.id,
        sender_id: rider.user.id,
        message: 'Rider has left the carpool.'
      })

    if current_user.commute.driver
      redirect_to show_rideshare_path
    else
      redirect_to edit_rider_path
    end
  end

  def show
    @message = Message.new

    if current_user.commute.driver != nil
      @riders = current_user.commute.driver.riders
    else
      @driver = current_user.commute.rider.rideshare.driver
    end
  end

  def update
    rideshare = Rideshare.find_by(driver_id: params[:id], rider_id: nil)
    message = Message.where(recipient_id: current_user.id, sender_id: params[:id], invite: true)
    rider = current_user.commute.rider

    if rideshare 
      rideshare.update(rider_id: rider.id)
      Rider.find(rider.id).update(looking: false)
      flash[:notice] = 'Carpool joined!'
      message.destroy_all
      redirect_to show_rideshare_path
    else
      flash[:alert] = 'Carpool full.  Invite is no longer valid.'
      message.destroy_all
      redirect_to edit_rider_path(current_user)
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/commute_helper.rb
module CommuteHelper
end

app/helpers/driver_helper.rb
module DriverHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/rider_helper.rb
module RiderHelper
end

app/helpers/rideshare_helper.rb
module RideshareHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/commute/edit.html.erb
<div class='container'>
	<div class='row'>
		<div>
			<h3 class=''>Double check your commute!</h3>
			<p>To make sure everything is correct (or should they wish to change anything), this page will display the information back to the user.  Here they can also decide if they want to be a driver (owner of a carpool) or a rider (belong to a carpool).  The map above will display any users within the search distance they provided in case they wish to send them a message by clicking the marker for the user and then the message icon.</p>
		</div>
	</div>
	<% if !current_user.commute.rider && !current_user.commute.driver %>
		<div class='row'>
			<br>
			<div class="col s6 center">
				<%= form_for @driver, url: driver_path do |f| %>
					<button class="btn waves-effect waves-light" type="submit" name="action">Become Driver
						<i class="mdi-notification-drive-eta"></i>
					</button>
					<%= f.hidden_field :user_id, value: current_user.id %>
					<%= f.hidden_field :commute_id, value: current_user.commute.id %>
				<% end %>
			</div>
			<div class="col s6 center">
				<%= form_for @rider, url: rider_path do |f| %>
					<button class="btn waves-effect waves-light" type="submit" name="action">Become Rider
						<i class="mdi-social-person-outline"></i>
					</button>
					<%= f.hidden_field :user_id, value: current_user.id %>
					<%= f.hidden_field :commute_id, value: current_user.commute.id %>
				<% end %>
			</div>
		</div>

	<% end %>
</div>

<div id="map-canvas" style="height: 50%; width: 66.6%; display: block; margin-left: auto; margin-right: auto;">
</div>

<div class='container'>
	<div class="row">
	<%= form_for @commute, :url => { :action => "update" } do |f| %>
		<div class="col s6">
			<div class="row">
				<div class="input-field">
					<%= f.label :meetup_street %>
					<%= f.text_field :meetup_street %>
				</div>
			</div>
			<div class="row">
				<div class="input-field">
					<%= f.label :meetup_city %>
					<%= f.text_field :meetup_city %>
				</div>
			</div>
			<div class="row">
				<div class="input-field">
					<%= f.label :meetup_state %>		
					<%= f.text_field :meetup_state %>
				</div>
			</div>
		</div>
		<div class="col s6">
			<div class="row">
				<div class="input-field">
					<%= f.label :dropoff_street %>
					<%= f.text_field :dropoff_street %>
				</div>
			</div>
			<div class="row">
				<div class="input-field">
					<%= f.label :dropoff_city %>
					<%= f.text_field :dropoff_city %>
				</div>
			</div>
			<div class="row">
				<div class="input-field">
					<%= f.label :dropoff_state %>
					<%= f.text_field :dropoff_state %>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col s4">
				<%= f.label :leave_time %>
				<%= f.select(:leave_time, class: 'leave-time-select') do %>
					<% [['06 AM', '06:00:00'],['07 AM', '07:00:00'],['08 AM', '08:00:00'],['09 AM', '09:00:00'],['10 AM', '10:00:00'],['11 AM', '11:00:00'],['12 AM', '12:00:00']].each do |c| -%>
						<%= content_tag(:option, c.first, value: c.last) %>
					<% end %>
				<% end %>
			</div>
			<div class="col s4">
				<%= f.label :return_time %>
				<%= f.select(:return_time, class: 'dropoff-time-select') do %>
					<% [['03 PM', '15:00:00'],['04 PM', '16:00:00'],['05 PM', '17:00:00'],['06 PM', '18:00:00'],['07 PM', '19:00:00'],['08 PM', '20:00:00'],['09 PM', '21:00:00']].each do |c| -%>
						<%= content_tag(:option, c.first, value: c.last) %>
					<% end %>
				<% end %>
			</div>
			<div class="col s4">
				<%= f.label :search_distance %>
				<p class="range-field">
    				<input type="range" name='commute[search_distance]' id="commute_search_distance" min="1" max="10" value="<%= @commute.search_distance || 5 %>"/>
  				</p>
			</div>
		</div>
		<%= f.hidden_field :meetup_lat %>
		<%= f.hidden_field :meetup_lng %>
		<%= f.hidden_field :dropoff_lat %>
		<%= f.hidden_field :dropoff_lng %>
		<div class="row">
			<div class="col s4">&nbsp;</div>
			<div class="col s4 center">
				<button id='edit-commute-button' class="btn waves-effect waves-light" type="submit" name="action">Edit Commute
	    			<i class="mdi-content-send right"></i>
	  			</button>
	<% end %>
			</div>
			<div class="col s4">&nbsp;</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	// Clear original Geocode incase user needs to update
	$(document).ready(function(){
		$('select').material_select()

		var leaveTime = "<%= @commute.leave_time.to_s.split(' ')[1] %>"
		var returnTime = "<%= @commute.return_time.to_s.split(' ')[1] %>"
		var leaveHour = leaveTime.split(':')[0] + ' AM'
		var returnHour = "0" + String(returnTime.split(':')[0] - 12 ) + ' PM'

		$('span.select-dropdown:first').text(leaveHour)
		$('#commute_leave_time').val(leaveTime)

		$('span.select-dropdown:last').text(returnHour)
		$('#commute_return_time').val(returnTime)

	})

	// Google Maps API for plotting directions and finding nearby riders.
	var directionsDisplay;
	var directionsService = new google.maps.DirectionsService();
	var map;
	var directions = []

	// Initializing the map as well as DirectionsRenderer and Geocoder
	function initialize() {
		geocoder = new google.maps.Geocoder();
		directionsDisplay = new google.maps.DirectionsRenderer();
		var austin = new google.maps.LatLng(30.264477, -97.746192);
		var mapOptions = {
		    zoom:11,
		    center: austin
		}
		map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
		directionsDisplay.setMap(map);
	}
    initialize();

    // Calculating and displaying the directions
	function calcRoute() {
		var start = document.getElementById("commute_meetup_street").value + " " + document.getElementById("commute_meetup_city").value + " " + document.getElementById("commute_meetup_state").value;
		var end = document.getElementById("commute_dropoff_street").value + " " + document.getElementById("commute_dropoff_city").value + " " + document.getElementById("commute_dropoff_state").value;
		var request = {
			origin:start,
			destination:end,
			travelMode: google.maps.TravelMode.DRIVING
		};
		directionsService.route(request, function(result, status) {
			if (status == google.maps.DirectionsStatus.OK) {
				directionsDisplay.setDirections(result);
				directions.push({
					k: result.routes[0].overview_path[0].k,
					D: result.routes[0].overview_path[0].D
				},{
					k: result.routes[0].overview_path[result.routes[0].overview_path.length-1].k,
					D: result.routes[0].overview_path[result.routes[0].overview_path.length-1].D
				})

				var infowindow = new google.maps.InfoWindow()
				var initial = directions[0]
				var riderCount = 0

				<% @commutes.each do |entry| %>

				var compare = {k: <%= entry.meetup_lat ? entry.meetup_lat : 0 %>, D: <%= entry.meetup_lng ? entry.meetup_lng : 0 %>}

				if (google.maps.geometry.spherical.computeDistanceBetween(initial, compare) < (<%= @commute.search_distance %> * 1600) ){

					var marker = new google.maps.Marker({
			    		position: new google.maps.LatLng(compare.k, compare.D),
			    		animation: google.maps.Animation.DROP,
			    		map: map
					});

					// '#sign_up_modal', class: "modal-trigger"

					google.maps.event.addListener(marker, 'click', (function(marker){
							return function() {
								// infowindow.setContent('<h6>Rider found!</h6><p><%= entry.meetup_street %></p><%= link_to "Invite Rider", "#rider_invite_modal", class: "modal-trigger" %>')
								infowindow.setContent("<h6>User found!</h6><p id='recipient-username' data-id='<%= entry.user_id %>'><%= User.find(entry.user_id).username %></p><a href='#rider_message_modal' class='modal-trigger waves-effect waves-light btn'><i class='mdi-communication-email'></i></a>")
		    					infowindow.open(map, marker);
							}

  					})(marker))
				}
				<% end %>

				google.maps.event.addListener(infowindow, 'domready', function() {
      				$('.modal-trigger').leanModal({
      					ready: function() {
      						var recipient = $('p#recipient-username').text()
      						var recipientId = $('p#recipient-username').attr('data-id')
    						$('#recipient').val(recipient)
    						$('#message_recipient_id').val(recipientId)
    					}
      				});
				});
			}
		});
	}
    calcRoute();
    // End of Google Maps API Implementation

    // Function for geocoding the Address, City, and State into LatLong.
	var geocoder;

    function codeAddress() {
	    var meetupAddress = document.getElementById("commute_meetup_street").value + " " + document.getElementById("commute_meetup_city").value + " " + document.getElementById("commute_meetup_state").value;
	    geocoder.geocode( { 'address': meetupAddress}, function(results, status) {
	    	if (status == google.maps.GeocoderStatus.OK) {
	        	// map.setCenter(results[0].geometry.location);
	        	// var marker = new google.maps.Marker({
	         //    	map: map,
	         //    	position: results[0].geometry.location
	        	// });
	    		console.log(results[0].geometry.location)
	    		$('#commute_meetup_lat').val(results[0].geometry.location.k)
	    		$('#commute_meetup_lng').val(results[0].geometry.location.D)
	    	} else {
	    		alert("Meet-up Geocode was not successful for the following reason: " + status);
	    	}
		});
		var dropoffAddress = document.getElementById("commute_dropoff_street").value + " " + document.getElementById("commute_dropoff_city").value + " " + document.getElementById("commute_dropoff_state").value;
	    geocoder.geocode( { 'address': dropoffAddress}, function(results, status) {
	    	if (status == google.maps.GeocoderStatus.OK) {
	        	// map.setCenter(results[0].geometry.location);
	        	// var marker = new google.maps.Marker({
	         //    	map: map,
	         //    	position: results[0].geometry.location
	        	// });
	    		console.log(results[0].geometry.location)
	    		$('#commute_dropoff_lat').val(results[0].geometry.location.k)
	    		$('#commute_dropoff_lng').val(results[0].geometry.location.D)
	    	} else {
	    		alert("Drop-off Geocode was not successful for the following reason: " + status);
	    	}
		});
	}
	// End of function

	$("button#edit-commute-button").hover(function(){
		codeAddress()
	})
</script>

<!-- Rider Invite Modal -->
<!-- <div id="rider_invite_modal" class="modal row">
	<div class="row">
		<div class="col s12">
			<h4>Send a message to the Rider.</h4>
		</div>
	</div>
	<form class="col s12">
    <div class="row">
      <div class="col s4">
        <label for="sender">Sender:</label>
        <input id="sender" type="text" class="validate" value='<%= current_user.username %>' disabled selected>
      </div>
      <div class="col s4">
        <label for="recipient">Recipient:</label>
        <input id="recipient" type="text" class="validate" disabled selected>
      </div>
    </div>
    <div class="row">
    	<div class="col s8">
	    	<textarea class="materialize-textarea" placeholder="Hey man!  Let's meet-up!"></textarea>
	        <label>Message:</label>
    	</div>
    	<div class="col s4">
    		<a href='#' class='waves-effect waves-light btn'>Send Message</a>
    	</div>
	</div>
  </form>
</div> -->
<!-- End Rider Invite Modal -->

<div id="rider_message_modal" class="modal row">
	<div class="row">
		<div class="col s12">
			<h4>Send a message to the Rider.</h4>
		</div>
	</div>
	<%= form_for @message, url: message_path, html: {class: 'col s12'} do |f| %>
    <div class="row">
      <div class="col s4">
        <label for="sender">Sender:</label>
        <input id="sender" type="text" class="validate" value='<%= current_user.username %>' disabled selected>
      </div>
      <div class="col s4">
        <label for="recipient">Recipient:</label>
        <input id="recipient" type="text" class="validate" disabled selected>
        <%= f.hidden_field :recipient_id %>
      </div>
    </div>
    <div class="row">
    	<div class="col s8">
	    	<!-- <textarea class="materialize-textarea" placeholder="Hey man!  Let's meet-up!"></textarea>
	        <label>Message:</label> -->
	        <%= f.label :message %>
	        <%= f.text_area :message, class: 'materialize-textarea' %>
    	</div>
    	<div class="col s4">
    		<button type='submit' class='waves-effect waves-light btn'>Send Message</button>
    	</div>
	</div>
  <% end %>
</div>

app/views/home/about.html.erb
<div class='container' style='min-height: 60%;'>
	<div class='row'>
		<h3>About me!</h3>
		<p>First of all thank you so much for checking out my web app!  I hope you enjoyed seeing my hardwork displayed in this proof of concept app.  Should you wish to find out more information about me, I will include all the relevant information.  Thanks again!</p>
	</div>

	<div class='row'>
		<div class='col s4'><img src="<%= image_path('ProfessionalPicture.jpg') %>" alt="" class="circle responsive-img"></div>
		<div class='col s8'>
			<h5>Bio:</h5>
			<p>I am a web developer by day and casual gamer by night. After a four year stint at Blizzard Entertainment, I enrolled in a software development career accelerator called MakerSquare to pursue full-stack web development full-time. This web app illustrates the breadth of material I learned while at MakerSquare, and was built in just over a week.</p>
		</div>
	</div>

	<div class='row'>
		<div class='col s6'>
			<h5>Relevant Links:</h5>
			<ul>
				<li><a href="mailto:glennmeyer@gmail.com">glennmeyer@gmail.com</a></li>
				<li><a href="https://www.linkedin.com/in/glennmeyercsm/en">LinkedIn</a></li>
				<li><a href="https://twitter.com/GlennFMeyer">Twitter</a></li>
				<li><a href="https://github.com/GlennMeyer">Github</a></li>
			</ul>
		</div>
		<div class='col s6'>
			<h5>Past Projects:</h5>
			<h6>At MakerSquare:</h6>
			<ul>
				<li><a href="http://cliqr.herokuapp.com">Cliqr</a></li>
			</ul>
			<h6>Before MakerSquare:</h6>
			<ul>
				<li><a href="http://www.avanti-technology.com/">Avanti Technology, Inc.</a></li>
				<li><a href="http://www.veteransride.org/">Defenders of Freedom: Veteran's Recognition Ride</a></li>
				<li><a href="http://www.wimberleyvfwrodeo.com/">Wimberley VFW Rodeo</a></li>
			</ul>
		</div>
	</div>
</div>

app/views/message/create.html.erb
<h1>Message#create</h1>
<p>Find me in app/views/message/create.html.erb</p>

app/views/message/index.html.erb
<div class='container' style='min-height: 60%;'>
  <div class='row'>
    <h3>Welcome to your inbox.</h3>
      <p>The topmost table is where you can view your inbox.  If the message is an invite, the left most button will allow you to accept the invitation.  Other than that, you can either reply directly to the message or delete it from the mail system.  Below that is the outbox for showing all of your sent messages.</p>
  </div>

  <!-- This is the inbox. -->

  <div class='row' style='min-height: 40%;'>
    <div class='col s12'>
      <table class="hoverable">
        <thead>
          <tr>
              <th data-field="sender">Sender</th>
              <th data-field="sent_at">Sent At</th>
              <th data-field="message">Message</th>
              <th data-field='approve'>Approve</th>
              <th data-field='reply'>Reply</th>
              <th data-field='delete'>Delete</th>
          </tr>
        </thead>

        <tbody>
          <% @inbox.each do |message| %>
            <% message.update(read: true) if message.read == false %>
            <tr>
          <td><%= User.find(message.sender_id).username %></td>
          <td><%= message.created_at.in_time_zone("Central Time (US & Canada)") %></td>
          <td><%= message.message %></td>
          <td>
            <% if message.invite == true %>
              <%= link_to accept_rideshare_path(User.find(message.sender_id).commute.driver.id), method: :put do %>
                <button class='waves-effect waves-light btn'><i class="mdi-navigation-check"></i></button>
                <% end %>
            <% end %>
          </td>
          <td><button href='#reply_modal' data-id="<%= message.sender_id %>" data-username="<%= User.find(message.sender_id).username %>" class='modal-trigger waves-effect waves-light btn'><i class="mdi-content-reply"></i></button></td>
          <td>
            <a href='<%= destroy_message_path(message.id) %>'>
            <button class='waves-effect waves-light btn red'><i class="mdi-action-delete"></i></button></a>
          </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  <!-- This is the Outbox -->

    <div class='row' style='min-height: 40%;'>
      <div class='col s12'>
        <table class="hoverable">
          <thead>
            <tr>
                <th data-field="sender">Recipient</th>
                <th data-field="sent_at">Sent At</th>
                <th data-field="message">Message</th>
                <th data-field='delete'>Delete</th>
                <th data-field='actions'>&nbsp;</th>
                <th data-field='actions'>&nbsp;</th>
            </tr>
          </thead>

          <tbody>
            <% @outbox.each do |message| %>
              <tr>
            <td><%= User.find(message.recipient_id).username %></td>
            <td><%= message.created_at.in_time_zone("Central Time (US & Canada)") %></td>
            <td><%= message.message %></td>
                <td>
                  <a href='<%= destroy_message_path(message.id) %>'>
                  <button class='waves-effect waves-light btn red'><i class="mdi-action-delete"></i></button></a>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="reply_modal" class="modal row">
  <div class="row">
    <div class="col s12">
      <h4>Reply to a message.</h4>
    </div>
  </div>
  <%= form_for @message, url: message_path, html: {class: 'col s12'} do |f| %>
    <div class="row">
      <div class="col s4">
        <label for="sender">Sender:</label>
        <input id="sender" type="text" class="validate" value='<%= current_user.username %>' disabled selected>
      </div>
      <div class="col s4">
        <label for="recipient">Recipient:</label>
        <input id="recipient" type="text" class="validate" disabled selected>
        <%= f.hidden_field :recipient_id %>
      </div>
    </div>
    <div class="row">
    	<div class="col s8">
	    	<!-- <textarea class="materialize-textarea" placeholder="Hey man!  Let's meet-up!"></textarea>
	        <label>Message:</label> -->
	        <%= f.label :message %>
	        <%= f.text_area :message, class: 'materialize-textarea' %>
    	</div>
    	<div class="col s4">
        <% if current_user.commute && current_user.commute.driver %>
          <p>
            <input name="message[invite]" type="radio" id="radio1" value='false' checked/>
            <label for="radio1">Message</label>
            <input name="message[invite]" type="radio" id="radio2" value='true' />
            <label for="radio2">Invite</label>
          </p>
        <% end %>
    		<button type='submit' class='waves-effect waves-light btn'>Send Message</button>
    	</div>
	</div>
  <% end %>
</div>

<script type="text/javascript">
	var recipientId
	var recipientUsername

	$('.modal-trigger').leanModal({
		ready: function(){
			$('#recipient').val(recipientUsername)
			$('#message_recipient_id').val(recipientId)
		}
	});

	$('.modal-trigger').click(function(){
		recipientId = $(this).attr('data-id')	
		recipientUsername = $(this).attr('data-username')
	})
</script>